name: .NET

on:
  push:
    branches: [ cicd ]
  pull_request:
    branches: [ cicd ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100

    # Publish to folder
    - name: Publish to folder
      run: dotnet publish ./DndBoard/Server --configuration Release
 
    # Deploy to ftp
    - name: Deploy to ftp
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.FTP_ADDRESS }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftps
        port: 21
        local-dir: /home/runner/work/DndBoard/DndBoard/DndBoard/Server/bin/Release/net5.0/publish/
